#!/bin/bash
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2013, Joyent, Inc.  All rights reserved.
#

#
# Given a root directory and a new rpath, sets the rpath via elfedit for all elf
# objects under a given tree.
#

shopt -s xpg_echo
set -o pipefail
unalias -a
export PATH=/usr/bin:/usr/sbin:/sbin

srp_arg0=$(basename $0)
srp_root=
srp_ld32=

function fatal
{
	local msg="$*"
	[[ -z "$msg" ]] && msg="failed"
	echo "$srp_arg0: $msg" >&2
	exit 1
}

function fix_file
{
	local file=$1

	elfedit -e "dyn:runpath $srp_ld32" $file
	[[ $? -eq 0 ]] || fatal "failed to set rpath on $file"
}

[[ $# -eq 2 ]] || fatal "<directory> <32-bit path>"
srp_root=$1
srp_ld32=$2

[[ -d $srp_root ]] || fatal "not a directory"

for f in $(find $srp_root -type f -exec file '{}' \; | grep ELF |
    grep -v ARM | grep -v relocatable | awk 'BEGIN{ FS=":" } { print $1 }'); do
	fix_file $f
done

exit 0
